# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1b56cdaadc9c2db052c90df8d4a5ba729d40afccfb2ba613f1eb1f6040a437a4856a13c01a70ed8b09b3a4ba28cc24ec9ab3b8d3afdee1230c0996776feded4

test:
  secret_key_base: fba8763b4a14026ac352606833bec0d2253c4005206940ca1be947f5bb7467bced175523f43709573a66a12ef73c044f1f0c287d737af1f1328de133c291e9a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
